extensions:
  - selva.ext.templates.jinja

templates:
  jinja:
    optimized: true
    extensions:
      - jinja2.ext.i18n
      - jinja2.ext.debug

logging:
  format: console
  level:
    uvicorn: info